export const CONSTRUCTOR_MODAL = 'CONSTRUCTOR_MODAL';
export const INGREDIENT_MODAL = 'INGREDIENT_MODAL';

export const INGREDIENTS_DATA = 'INGREDIENTS_DATA';
export const INGREDIENTS_CHOOSE = 'INGREDIENTS_CHOOSE';
export const INGREDIENT_DELETE = 'INGREDIENT_DELETE';
export const COUNTER_DECREASE = 'COUNTER_DECREASE';
export const COUNTER_INCREASE = 'COUNTER_INCREASE';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';