export const CONSTRUCTOR_MODAL: 'CONSTRUCTOR_MODAL' = 'CONSTRUCTOR_MODAL';

export const INGREDIENTS_DATA: 'INGREDIENTS_DATA' = 'INGREDIENTS_DATA';
export const INGREDIENTS_CHOOSE: 'INGREDIENTS_CHOOSE' = 'INGREDIENTS_CHOOSE';
export const INGREDIENT_DELETE: 'INGREDIENT_DELETE' = 'INGREDIENT_DELETE';
export const COUNTER_DECREASE: 'COUNTER_DECREASE' = 'COUNTER_DECREASE';
export const COUNTER_INCREASE: 'COUNTER_INCREASE' = 'COUNTER_INCREASE';
export const MOVE_INGREDIENT: 'MOVE_INGREDIENT' = 'MOVE_INGREDIENT';

export const ORDER_LOAD: 'ORDER_LOAD' = 'ORDER_LOAD';
export const RESET_CONSTRUCTOR: 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';
export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';

export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN: 'LOGIN' = 'LOGIN';
export const LOGOUT: 'LOGOUT' = 'LOGOUT';
export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';



